language:
  node_js
node_js:
  "11.12.0"

cache:
  directories:
    - node_modules

before_script:
  - npm install
  - npm install coveralls

script:
  - npm run coverage
  - npm run test
  - npm run coveralls
